### ISSUE TITLE
Missing of geomagic_touch_x_ros repository

### ISSUE THREAD

**Issue by BCYounker** [ros-pybullet/ros_pybullet_interface#11]
I would be very appreciated if you could re-upload the repo related to TouchX.

**Comment by cmower** [comment]
Thanks for this @BCYounker, you can find the driver [here](https://github.com/ros-pybullet/geomagic_touch_x_ros_driver). It assumes you have the OpenHaptics Developer software installed (we used v3.4.0) from 3D Systems (this is not something we can provide), but if you have the Touch X device then you should have access to the software.

I will close this issue now, but please feel free to open another in the `geomagic_touch_x_ros_driver` if you have any issues.
