### ISSUE TITLE
How to add motor inertia

### ISSUE THREAD

**Issue by rua0ra1** [ros-pybullet/ros_pybullet_interface#3]
Hi, 
I am not sure whether it is right place to ask this question. I am quite new to ros and pybullet. One of the main issue, I am facing is including motor inertia  while simulating the robot. Mujoco has this option to add motor inertia to the joints. I really appreciate it if you can  provide you suggestions to add motor inertia in the simulation. Thank you

**Comment by cmower** [comment]
Hi @RamCharanThota, this should be specified in the URDF, see [here](http://wiki.ros.org/urdf/Tutorials/Adding%20Physical%20and%20Collision%20Properties%20to%20a%20URDF%20Model). Once you have specified that in the URDF, then PyBullet should load these parameters automatically.

**Comment by rua0ra1** [comment]
Thank you for answering my question @cmower. I really appreciate it.

**Comment by cmower** [comment]
No problem @RamCharanThota!
